/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as R404RouteImport } from './routes/404'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char123Char125DotmdRouteImport } from './routes/{$}[.]md'
import { Route as ApiSearchDotjsonRouteImport } from './routes/api/search[.]json'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AppsSlugRouteImport } from './routes/apps/$slug'
import { Route as CategoriesIdRouteImport } from './routes/categories/$id'
import { Route as DeployIndexRouteImport } from './routes/deploy/index'
import { Route as DeployCallbackRouteImport } from './routes/deploy/callback'
import { Route as InstallIndexRouteImport } from './routes/install/index'
import { Route as InstallSlugRouteImport } from './routes/install/$slug'
import { Route as MyIndexRouteImport } from './routes/my/index'
import { Route as OgSplatRouteImport } from './routes/og/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123Char125DotmdRoute = Char123Char125DotmdRouteImport.update({
  id: '/{$}.md',
  path: '/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchDotjsonRoute = ApiSearchDotjsonRouteImport.update({
  id: '/api/search.json',
  path: '/api/search.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIdRoute = CategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployIndexRoute = DeployIndexRouteImport.update({
  id: '/deploy/',
  path: '/deploy/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployCallbackRoute = DeployCallbackRouteImport.update({
  id: '/deploy/callback',
  path: '/deploy/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallIndexRoute = InstallIndexRouteImport.update({
  id: '/install/',
  path: '/install/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallSlugRoute = InstallSlugRouteImport.update({
  id: '/install/$slug',
  path: '/install/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MyIndexRoute = MyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgSplatRoute = OgSplatRouteImport.update({
  id: '/og/$',
  path: '/og/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$}.md': typeof Char123Char125DotmdRoute
  '/api/search.json': typeof ApiSearchDotjsonRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/deploy/callback': typeof DeployCallbackRoute
  '/install/$slug': typeof InstallSlugRoute
  '/og/$': typeof OgSplatRoute
  '/apps/': typeof AppsIndexRoute
  '/deploy/': typeof DeployIndexRoute
  '/install/': typeof InstallIndexRoute
  '/my/': typeof MyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$}.md': typeof Char123Char125DotmdRoute
  '/api/search.json': typeof ApiSearchDotjsonRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/deploy/callback': typeof DeployCallbackRoute
  '/install/$slug': typeof InstallSlugRoute
  '/og/$': typeof OgSplatRoute
  '/apps': typeof AppsIndexRoute
  '/deploy': typeof DeployIndexRoute
  '/install': typeof InstallIndexRoute
  '/my': typeof MyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$}.md': typeof Char123Char125DotmdRoute
  '/api/search.json': typeof ApiSearchDotjsonRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/deploy/callback': typeof DeployCallbackRoute
  '/install/$slug': typeof InstallSlugRoute
  '/og/$': typeof OgSplatRoute
  '/apps/': typeof AppsIndexRoute
  '/deploy/': typeof DeployIndexRoute
  '/install/': typeof InstallIndexRoute
  '/my/': typeof MyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/404'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/{$}.md'
    | '/api/search.json'
    | '/apps/$slug'
    | '/categories/$id'
    | '/deploy/callback'
    | '/install/$slug'
    | '/og/$'
    | '/apps/'
    | '/deploy/'
    | '/install/'
    | '/my/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/404'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/{$}.md'
    | '/api/search.json'
    | '/apps/$slug'
    | '/categories/$id'
    | '/deploy/callback'
    | '/install/$slug'
    | '/og/$'
    | '/apps'
    | '/deploy'
    | '/install'
    | '/my'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/404'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/{$}.md'
    | '/api/search.json'
    | '/apps/$slug'
    | '/categories/$id'
    | '/deploy/callback'
    | '/install/$slug'
    | '/og/$'
    | '/apps/'
    | '/deploy/'
    | '/install/'
    | '/my/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R404Route: typeof R404Route
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123Char125DotmdRoute: typeof Char123Char125DotmdRoute
  ApiSearchDotjsonRoute: typeof ApiSearchDotjsonRoute
  AppsSlugRoute: typeof AppsSlugRoute
  CategoriesIdRoute: typeof CategoriesIdRoute
  DeployCallbackRoute: typeof DeployCallbackRoute
  InstallSlugRoute: typeof InstallSlugRoute
  OgSplatRoute: typeof OgSplatRoute
  AppsIndexRoute: typeof AppsIndexRoute
  DeployIndexRoute: typeof DeployIndexRoute
  InstallIndexRoute: typeof InstallIndexRoute
  MyIndexRoute: typeof MyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{$}.md': {
      id: '/{$}.md'
      path: '/{$}.md'
      fullPath: '/{$}.md'
      preLoaderRoute: typeof Char123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search.json': {
      id: '/api/search.json'
      path: '/api/search.json'
      fullPath: '/api/search.json'
      preLoaderRoute: typeof ApiSearchDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$id': {
      id: '/categories/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof CategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy/': {
      id: '/deploy/'
      path: '/deploy'
      fullPath: '/deploy/'
      preLoaderRoute: typeof DeployIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy/callback': {
      id: '/deploy/callback'
      path: '/deploy/callback'
      fullPath: '/deploy/callback'
      preLoaderRoute: typeof DeployCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/': {
      id: '/install/'
      path: '/install'
      fullPath: '/install/'
      preLoaderRoute: typeof InstallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/$slug': {
      id: '/install/$slug'
      path: '/install/$slug'
      fullPath: '/install/$slug'
      preLoaderRoute: typeof InstallSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/': {
      id: '/my/'
      path: '/my'
      fullPath: '/my/'
      preLoaderRoute: typeof MyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$': {
      id: '/og/$'
      path: '/og/$'
      fullPath: '/og/$'
      preLoaderRoute: typeof OgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R404Route: R404Route,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123Char125DotmdRoute: Char123Char125DotmdRoute,
  ApiSearchDotjsonRoute: ApiSearchDotjsonRoute,
  AppsSlugRoute: AppsSlugRoute,
  CategoriesIdRoute: CategoriesIdRoute,
  DeployCallbackRoute: DeployCallbackRoute,
  InstallSlugRoute: InstallSlugRoute,
  OgSplatRoute: OgSplatRoute,
  AppsIndexRoute: AppsIndexRoute,
  DeployIndexRoute: DeployIndexRoute,
  InstallIndexRoute: InstallIndexRoute,
  MyIndexRoute: MyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
