import { index, integer, primaryKey, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { AUTO_UPDATE_CHOICES } from "../auto-update/auto-update";
import { WORKERS_DEV_CHOICES } from "../installs/workers-dev";
import { user } from "./auth-schema";

/**
 * The manager's D1 schema. Better Auth's tables (`user`, `session`,
 * `account`, `verification`, `rate_limit`, with the admin plugin's fields, and
 * the passkey plugin's `passkey`) live in
 * `auth-schema.ts`, generated by Better Auth's CLI, and the notification
 * tables in `notifications/schema.ts`; both are re-exported here so
 * drizzle-kit sees one schema. Timestamps are integer epoch milliseconds.
 */
export * from "../notifications/schema";
export * from "./auth-schema";

const timestamp = (name: string) => integer(name, { mode: "timestamp_ms" });

export const INSTALL_STATUSES = [
  "installing",
  "installed",
  "updating",
  "failed",
  "uninstalling",
  "uninstalled",
] as const;

/**
 * The last health check of an install's Worker URL: `verified` (it answered,
 * anything but a 5xx), `unverified` (no answer, or the edge's route-not-live
 * page), `unhealthy` (it answered with a 5xx).
 */
export const HEALTH_STATUSES = ["verified", "unverified", "unhealthy"] as const;
export type HealthStatus = (typeof HEALTH_STATUSES)[number];

export const RESOURCE_KINDS = [
  "worker",
  "kv",
  "d1",
  "r2",
  "queue",
  "queue_consumer",
  "vectorize",
  "durable_object",
  "workflow",
  "cron",
  "secret",
  "subdomain",
  "ratelimit",
  "domain",
  "custom_hostname",
  "email_route",
] as const;

/**
 * How an install's running code was built: `artifact`, a release catalog CI
 * built and signed; `sandbox`, built from the pinned commit by the sandbox
 * Worker in this account, unsigned; `self-deploying`, deployed by the app's
 * own installer, which the sandbox Worker ran at the pinned commit with the
 * app's own token. For a self-deploying install, `manifest_json` holds the
 * catalog manifest (there is no artifact manifest), `artifact_url` and
 * `artifact_digest` name the published catalog manifest, `worker_name` is
 * the Worker that serves the app, and every resource is `managed_by: "app"`.
 */
export const BUILD_KINDS = ["artifact", "sandbox", "self-deploying"] as const;
export type BuildKind = (typeof BUILD_KINDS)[number];

/**
 * Where an install's code comes from: `catalog`, the catalog's own release
 * or pinned build; `repository`, a GitHub repository an admin named,
 * built in this account and never reviewed by the catalog (it is shown as
 * "Not from the catalog, not checked" and never updated on its own); or
 * `source`, a catalog app an admin built from source at another commit, with
 * the catalog manifest but code the catalog did not check. For the last two,
 * `source_url` is the repository, `source_ref` the branch, tag or commit it
 * was built from, and `pin_sha` the commit.
 */
export const INSTALL_ORIGINS = ["catalog", "repository", "source"] as const;
export type InstallOrigin = (typeof INSTALL_ORIGINS)[number];

/**
 * Who owns a resource's lifecycle: `appflare`, which created it and deletes
 * it on uninstall, or `app`, the app's own installer, which the manager only
 * records and never deletes.
 */
export const RESOURCE_MANAGERS = ["appflare", "app"] as const;

/**
 * `reconfigure` redeploys an installed app's current version with changed
 * settings (vars), secrets, or Email Routing zone. `sandbox_enable` and
 * `sandbox_update` deploy the sandbox Worker release this manager pins (with
 * its bucket and container applications) and connect the manager to it;
 * `sandbox_disable` removes all of that again. None of the three has an
 * install. `self_rollback` redeploys an earlier version of the manager's own
 * Worker; it runs inside the request that asks for it, so it has no Workflow
 * instance (like a database restore). `source_build` builds a repository (or
 * a catalog app at another commit) in the sandbox Worker for an admin to
 * review; installing or updating from the build is a job of its own.
 */
export const JOB_KINDS = [
  "install",
  "update",
  "uninstall",
  "rollback",
  "self_update",
  "reconfigure",
  "sandbox_enable",
  "sandbox_update",
  "sandbox_disable",
  "self_rollback",
  "source_build",
] as const;
export type JobKind = (typeof JOB_KINDS)[number];

export const JOB_STATUSES = ["queued", "running", "succeeded", "failed"] as const;

/**
 * Who started a job: `admin`, a signed-in admin (every job before automatic
 * updates existed), or `schedule`, the cron, which starts updates of apps and
 * of Appflare itself when automatic updates are on.
 */
export const JOB_STARTERS = ["admin", "schedule"] as const;
export type JobStarter = (typeof JOB_STARTERS)[number];

export const LOG_LEVELS = ["debug", "info", "warn", "error"] as const;

/**
 * Key/value manager state: `schema_version` (3.1.4), the `migration_lock` row,
 * and later the discovered account id and Worker name (3.1.1).
 */
export const settings = sqliteTable("settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updated_at: timestamp("updated_at").notNull(),
});

/** One installed app instance (glossary: install). `id` is a ULID. */
export const installs = sqliteTable("installs", {
  id: text("id").primaryKey(),
  app_slug: text("app_slug").notNull(),
  /** The unique key of an active install: two installs that are not uninstalled never share it. */
  worker_name: text("worker_name").notNull(),
  /**
   * The label older managers show: the display name, else the Worker name.
   * Superseded by `display_name` and kept in step with it, so a manager
   * rolled back to such a version still shows the name an admin chose.
   */
  instance_name: text("instance_name"),
  /**
   * The name an admin gave the install ("Team link shortener"); null shows
   * the Worker name. UI only: never part of usage data.
   */
  display_name: text("display_name"),
  catalog_version: text("catalog_version").notNull(),
  artifact_url: text("artifact_url").notNull(),
  artifact_digest: text("artifact_digest"),
  pin_sha: text("pin_sha"),
  status: text("status", { enum: INSTALL_STATUSES }).notNull(),
  /** Workers version id currently deployed. */
  current_version_id: text("current_version_id"),
  /** User-entered vars (never secrets). */
  config_json: text("config_json"),
  /** Snapshot of the artifact manifest the install was made from. */
  manifest_json: text("manifest_json"),
  /**
   * The last Durable Object migration tag applied to the Worker; null when it
   * has none (or, for installs made before this was recorded, the last tag of
   * `manifest_json`).
   */
  do_migration_tag: text("do_migration_tag"),
  /** How the running code was built (see `BUILD_KINDS`). */
  build_kind: text("build_kind", { enum: BUILD_KINDS }).notNull().default("artifact"),
  /** For a sandbox build: the container image that built it. */
  sandbox_image: text("sandbox_image"),
  /** For a sandbox build: when the build finished. */
  built_at: timestamp("built_at"),
  /** Where the code comes from (see `INSTALL_ORIGINS`). */
  origin: text("origin", { enum: INSTALL_ORIGINS }).notNull().default("catalog"),
  /** Not from the catalog: the repository, `https://github.com/<owner>/<repo>`. */
  source_url: text("source_url"),
  /** Not from the catalog: the branch, tag or commit it was built from. */
  source_ref: text("source_ref"),
  /** The last health check's result; null until one ran. Never fails a job. */
  health_status: text("health_status", { enum: HEALTH_STATUSES }),
  /** When the last health check probed the Worker. */
  health_checked_at: timestamp("health_checked_at"),
  /** Whether the cron may update this install on its own (see `AUTO_UPDATE_CHOICES`). */
  auto_update: text("auto_update", { enum: AUTO_UPDATE_CHOICES }).notNull().default("inherit"),
  /**
   * The catalog version the cron left for an admin (its update needs a
   * secret or a confirmation); the cron does not try it again, only a newer one.
   */
  auto_update_waiting: text("auto_update_waiting"),
  /**
   * Whether the Worker answers on its workers.dev URL. Every deploy sends it,
   * with version previews always on (update checks use them). Turned off only
   * while a custom or external domain serves the app.
   */
  workers_dev_enabled: integer("workers_dev_enabled", { mode: "boolean" }).notNull().default(true),
  /**
   * Who sets `workers_dev_enabled` (see `WORKERS_DEV_CHOICES`): `auto` turns
   * it off when a custom or external domain goes live and back on when the
   * last live one is removed; `manual` once an admin used the switch.
   */
  workers_dev_choice: text("workers_dev_choice", { enum: WORKERS_DEV_CHOICES })
    .notNull()
    .default("auto"),
  /**
   * The custom or external domain that answered as the app when workers.dev
   * was turned off: the app's primary address while it is still attached
   * (else its first live domain).
   */
  served_domain: text("served_domain"),
  /**
   * For an app of several Workers: the version each Worker other than the
   * primary one serves, as the last job left it, `{ [Worker name]: version
   * id }`. Null for an app of one Worker (its version is
   * `current_version_id`), or while not known.
   */
  worker_versions_json: text("worker_versions_json"),
  installed_at: timestamp("installed_at").notNull(),
  updated_at: timestamp("updated_at").notNull(),
  /** Set when the uninstall job finishes (status `uninstalled`). */
  uninstalled_at: timestamp("uninstalled_at"),
  /**
   * Set when an admin forgets an uninstalled install: it leaves the list of
   * removed apps. Its row, its jobs, and any resources it kept in the account
   * stay as they are.
   */
  forgotten_at: timestamp("forgotten_at"),
  /**
   * The catalog the app comes from (`catalogs.id`): `official`, or a custom
   * catalog an admin added. Updates, form revisions and install checks follow
   * that catalog only, and its keys verify every release. Null for an install
   * from a repository, which no catalog lists.
   */
  catalog_id: text("catalog_id"),
});

/** `official`: the catalog Appflare ships with; `custom`: one an admin added. */
export const CATALOG_KINDS = ["official", "custom"] as const;
export type CatalogKind = (typeof CATALOG_KINDS)[number];

/**
 * The catalogs this manager browses and installs from. The official one is
 * seeded by its migration, can be turned off but never removed, and is always
 * verified with the signing keys built into Appflare (its `keys_json` and
 * `index_url` only describe them). A custom catalog is added by an admin with
 * its index URL and the public keys its releases are signed with, pinned
 * here: its artifacts and revised catalog manifests verify with these keys
 * only, and no custom key ever verifies another catalog's releases.
 */
export const catalogs = sqliteTable("catalogs", {
  /** `official`, or a short lowercase id derived from the label; prefixes the catalog's app keys. */
  id: text("id").primaryKey(),
  kind: text("kind", { enum: CATALOG_KINDS }).notNull(),
  label: text("label").notNull(),
  /** A Kumo badge colour (`CATALOG_COLOURS`). */
  colour: text("colour").notNull(),
  /** The https URL of the catalog's `index.json`. */
  index_url: text("index_url").notNull(),
  /** The pinned public keys, `[{ keyId, publicKeyBase64 }]`. */
  keys_json: text("keys_json").notNull(),
  /** Off: its apps are not browsed and its index is not refreshed. */
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
  added_at: timestamp("added_at").notNull(),
  /** When its index was last fetched (or found unchanged); null until then. */
  refreshed_at: timestamp("refreshed_at"),
  /** Why the last refresh failed; null after a successful one. */
  refresh_error: text("refresh_error"),
});

/** A Cloudflare object created for an install (glossary: resource). */
export const resources = sqliteTable(
  "resources",
  {
    id: text("id").primaryKey(),
    install_id: text("install_id")
      .notNull()
      .references(() => installs.id),
    kind: text("kind", { enum: RESOURCE_KINDS }).notNull(),
    binding: text("binding"),
    name: text("name").notNull(),
    cf_id: text("cf_id"),
    created_at: timestamp("created_at").notNull(),
    /** Deleted from the account (by an uninstall). */
    deleted_at: timestamp("deleted_at"),
    /** Kept in the account when its install was uninstalled, so it stays findable. */
    retained_at: timestamp("retained_at"),
    /** Who deletes it: Appflare, or the app's own installer (never Appflare). */
    managed_by: text("managed_by", { enum: RESOURCE_MANAGERS }).notNull().default("appflare"),
    /**
     * A custom or external domain: when a request through it first reached
     * the app. Until then it is not an address the app is opened at.
     */
    live_at: timestamp("live_at"),
  },
  (t) => [index("resources_install_id_idx").on(t.install_id)],
);

/** One asynchronous operation, run as a `JobWorkflow` instance (glossary: job). */
export const jobs = sqliteTable(
  "jobs",
  {
    id: text("id").primaryKey(),
    install_id: text("install_id").references(() => installs.id),
    kind: text("kind", { enum: JOB_KINDS }).notNull(),
    status: text("status", { enum: JOB_STATUSES }).notNull(),
    workflow_instance_id: text("workflow_instance_id"),
    /** Job input with secret values removed (names only). */
    input_json: text("input_json"),
    error: text("error"),
    /** The Workers version the job uploaded (update) or deployed (rollback). */
    worker_version_id: text("worker_version_id"),
    /**
     * Self-update only: the Appflare version the job is promoting, written
     * right before the promotion. The new version completes a job left
     * running only when this names it, so a preview request (which runs the
     * new code before the switch) can never complete the job.
     */
    promoting_version: text("promoting_version"),
    /** Who started the job (see `JOB_STARTERS`). */
    started_by: text("started_by", { enum: JOB_STARTERS }).notNull().default("admin"),
    started_at: timestamp("started_at"),
    finished_at: timestamp("finished_at"),
  },
  (t) => [index("jobs_install_id_idx").on(t.install_id)],
);

/** Job log lines, written in batches per step. */
export const job_logs = sqliteTable(
  "job_logs",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    job_id: text("job_id")
      .notNull()
      .references(() => jobs.id),
    ts: timestamp("ts").notNull(),
    level: text("level", { enum: LOG_LEVELS }).notNull(),
    message: text("message").notNull(),
    data_json: text("data_json"),
  },
  (t) => [index("job_logs_job_id_idx").on(t.job_id)],
);

/**
 * Recovery data taken before an update or a settings change (glossary:
 * snapshot): the Worker version that was serving, a D1 Time Travel bookmark
 * per database, and the install's catalog state and settings at that moment,
 * so a rollback can put all of it back.
 * A snapshot of the manager itself (taken by its self-update) has no install:
 * `install_id` is null, `catalog_version` is the manager's version before the
 * update and `target_catalog_version` the one it moved to.
 */
export const snapshots = sqliteTable(
  "snapshots",
  {
    id: text("id").primaryKey(),
    /** Null for a snapshot of the manager itself. */
    install_id: text("install_id").references(() => installs.id),
    /** The update job that took it. */
    job_id: text("job_id")
      .notNull()
      .references(() => jobs.id),
    worker_version_id: text("worker_version_id").notNull(),
    /** `{ [database_id]: bookmark }` */
    d1_bookmarks_json: text("d1_bookmarks_json").notNull(),
    taken_at: timestamp("taken_at").notNull(),
    /** The install's `catalog_version` before the update. */
    catalog_version: text("catalog_version"),
    /** The install's `manifest_json` before the update. */
    manifest_json: text("manifest_json"),
    artifact_url: text("artifact_url"),
    artifact_digest: text("artifact_digest"),
    pin_sha: text("pin_sha"),
    do_migration_tag: text("do_migration_tag"),
    /** The install's build provenance before the update, restored by a rollback. */
    build_kind: text("build_kind", { enum: BUILD_KINDS }).notNull().default("artifact"),
    sandbox_image: text("sandbox_image"),
    built_at: timestamp("built_at"),
    /** The install's origin before the update, restored by a rollback. */
    origin: text("origin", { enum: INSTALL_ORIGINS }).notNull().default("catalog"),
    source_url: text("source_url"),
    source_ref: text("source_ref"),
    /** The catalog version the update moved to. */
    target_catalog_version: text("target_catalog_version"),
    /**
     * The install's `config_json` (the settings the admin changed) before the
     * job, `{}` when there were none; null for snapshots taken before it was
     * recorded.
     */
    config_json: text("config_json"),
    /**
     * For an app of several Workers: the version each Worker other than the
     * primary one served, `{ [Worker name]: version id }`. Null for an app of
     * one Worker, whose version is `worker_version_id`.
     */
    worker_versions_json: text("worker_versions_json"),
  },
  (t) => [index("snapshots_install_id_idx").on(t.install_id)],
);

/**
 * Sponsored catalog items a user has hidden, by the item's id in the index.
 * Per user, because members browse the catalog too and hiding an item is not
 * a manager setting. A row for an item the index no longer lists is harmless.
 */
export const featured_dismissals = sqliteTable(
  "featured_dismissals",
  {
    user_id: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    item_id: text("item_id").notNull(),
    dismissed_at: timestamp("dismissed_at").notNull(),
  },
  (t) => [primaryKey({ columns: [t.user_id, t.item_id] })],
);

/**
 * Revised catalog manifests, one per signed release: the form and copy the
 * catalog published for a release after it was built (a higher `revision`
 * under the same pin; see `@appflare/schema` `revision.ts`). Keyed by the
 * release's `manifest.json` sha256, which is what `installs.artifact_digest`
 * and `snapshots.artifact_digest` record, so every install of that release,
 * and a rollback to it, reads the newest revision this manager has verified.
 * A row only moves to a higher (or equal) revision. Only verified manifests
 * are written (`catalog/revisions.server.ts`); the signed `manifest.json` in
 * `installs.manifest_json` is never changed.
 */
export const catalog_revisions = sqliteTable("catalog_revisions", {
  artifact_digest: text("artifact_digest").primaryKey(),
  revision: integer("revision").notNull(),
  /** sha256 of `catalog_json`, as the catalog index listed it. */
  sha256: text("sha256").notNull(),
  /** The catalog's signing key that signed `catalog_json` (the release's own key id). */
  key_id: text("key_id").notNull(),
  /** Base64 Ed25519 signature over `catalog_json`, verified before the row was written. */
  signature: text("signature").notNull(),
  /** The revised catalog manifest, exactly as published. */
  catalog_json: text("catalog_json").notNull(),
  recorded_at: timestamp("recorded_at").notNull(),
});

export const SOURCE_BUILD_STATUSES = ["building", "built", "failed", "used", "discarded"] as const;
export type SourceBuildStatus = (typeof SOURCE_BUILD_STATUSES)[number];

/** What a source build is for: a new install, or an update of an existing one. */
export const SOURCE_BUILD_PURPOSES = ["install", "update"] as const;
export type SourceBuildPurpose = (typeof SOURCE_BUILD_PURPOSES)[number];

/**
 * A build of a repository (or of a catalog app at another commit) in the
 * sandbox Worker, waiting for an admin's review. Its id is its
 * `source_build` job's. `status`: `building` while the job runs, `built`
 * once the artifact is stored and verified, `failed`, `used` once an install
 * or update job took it, `discarded` when the admin threw it away. The
 * artifact lives in the sandbox Worker's bucket under
 * `builds/<install_id>/<version>/`; `install_id` is the install it is for,
 * which for a new install does not exist until the admin installs.
 */
export const source_builds = sqliteTable(
  "source_builds",
  {
    id: text("id").primaryKey(),
    install_id: text("install_id").notNull(),
    purpose: text("purpose", { enum: SOURCE_BUILD_PURPOSES }).notNull(),
    /** `repository`, or `source` for a catalog app built at another commit. */
    origin: text("origin", { enum: INSTALL_ORIGINS }).notNull(),
    /** The catalog app, for a build from source; null for a repository. */
    app_slug: text("app_slug"),
    /** `owner/repo` on GitHub. */
    repo: text("repo").notNull(),
    /** The branch, tag or commit asked for; null for the default branch. */
    requested_ref: text("requested_ref"),
    /** The build command choice (`buildCommandChoiceSchema`), as JSON. */
    build_command_json: text("build_command_json"),
    status: text("status", { enum: SOURCE_BUILD_STATUSES }).notNull(),
    /** Set once built: what was built, and where it is. */
    commit_sha: text("commit_sha"),
    ref: text("ref"),
    version: text("version"),
    digest: text("digest"),
    manifest_key: text("manifest_key"),
    artifact_key: text("artifact_key"),
    image: text("image"),
    /** The verified artifact manifest, exactly as stored (its sha256 is `digest`). */
    manifest_json: text("manifest_json"),
    /** What the sandbox Worker worked out (`repositoryDetectionSchema`), as JSON. */
    detected_json: text("detected_json"),
    built_at: timestamp("built_at"),
    created_at: timestamp("created_at").notNull(),
    updated_at: timestamp("updated_at").notNull(),
  },
  (t) => [index("source_builds_install_id_idx").on(t.install_id)],
);

/**
 * GitHub access tokens an admin added (Settings, Account): fine-grained,
 * read-only tokens for building private repositories. Only the record is
 * here; each token's value is a secret on the sandbox Worker
 * (`githubTokenSecretName(id)`), never in this database. Disabling sandbox
 * builds deletes that Worker, and with it every token, so the rows go too.
 */
export const github_tokens = sqliteTable("github_tokens", {
  /** A ULID; also names the token's secret on the sandbox Worker. */
  id: text("id").primaryKey(),
  label: text("label").notNull(),
  /** The repositories it covers, as the admin describes them (`acme/api, acme/*`). */
  repositories: text("repositories").notNull(),
  /** Appflare reads its own releases with this token (at most one row). */
  for_releases: integer("for_releases", { mode: "boolean" }).notNull().default(false),
  created_at: timestamp("created_at").notNull(),
  last_used_at: timestamp("last_used_at"),
});
