import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

/**
 * The manager's D1 schema. Better Auth's tables (`user`, `session`,
 * `account`, `verification`, with the admin plugin's fields) live in
 * `auth-schema.ts`, generated by Better Auth's CLI, and are re-exported here so
 * drizzle-kit sees one schema. Timestamps are integer epoch milliseconds.
 */
export * from "./auth-schema";

const timestamp = (name: string) => integer(name, { mode: "timestamp_ms" });

export const INSTALL_STATUSES = [
  "installing",
  "installed",
  "updating",
  "failed",
  "uninstalling",
  "uninstalled",
] as const;

export const RESOURCE_KINDS = [
  "worker",
  "kv",
  "d1",
  "r2",
  "queue",
  "vectorize",
  "durable_object",
  "workflow",
  "cron",
  "secret",
  "subdomain",
] as const;

export const JOB_KINDS = ["install", "update", "uninstall", "rollback", "self_update"] as const;
export type JobKind = (typeof JOB_KINDS)[number];

export const JOB_STATUSES = ["queued", "running", "succeeded", "failed"] as const;

export const LOG_LEVELS = ["debug", "info", "warn", "error"] as const;

/**
 * Key/value manager state: `schema_version` (3.1.4), the `migration_lock` row,
 * and later the discovered account id and Worker name (3.1.1).
 */
export const settings = sqliteTable("settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updated_at: timestamp("updated_at").notNull(),
});

/** One installed app instance (glossary: install). `id` is a ULID. */
export const installs = sqliteTable("installs", {
  id: text("id").primaryKey(),
  app_slug: text("app_slug").notNull(),
  worker_name: text("worker_name").notNull(),
  instance_name: text("instance_name"),
  catalog_version: text("catalog_version").notNull(),
  artifact_url: text("artifact_url").notNull(),
  artifact_digest: text("artifact_digest"),
  pin_sha: text("pin_sha"),
  status: text("status", { enum: INSTALL_STATUSES }).notNull(),
  /** Workers version id currently deployed. */
  current_version_id: text("current_version_id"),
  /** User-entered vars (never secrets). */
  config_json: text("config_json"),
  /** Snapshot of the artifact manifest the install was made from. */
  manifest_json: text("manifest_json"),
  installed_at: timestamp("installed_at").notNull(),
  updated_at: timestamp("updated_at").notNull(),
});

/** A Cloudflare object created for an install (glossary: resource). */
export const resources = sqliteTable(
  "resources",
  {
    id: text("id").primaryKey(),
    install_id: text("install_id")
      .notNull()
      .references(() => installs.id),
    kind: text("kind", { enum: RESOURCE_KINDS }).notNull(),
    binding: text("binding"),
    name: text("name").notNull(),
    cf_id: text("cf_id"),
    created_at: timestamp("created_at").notNull(),
    deleted_at: timestamp("deleted_at"),
  },
  (t) => [index("resources_install_id_idx").on(t.install_id)],
);

/** One asynchronous operation, run as a `JobWorkflow` instance (glossary: job). */
export const jobs = sqliteTable(
  "jobs",
  {
    id: text("id").primaryKey(),
    install_id: text("install_id").references(() => installs.id),
    kind: text("kind", { enum: JOB_KINDS }).notNull(),
    status: text("status", { enum: JOB_STATUSES }).notNull(),
    workflow_instance_id: text("workflow_instance_id"),
    /** Job input with secret values removed (names only). */
    input_json: text("input_json"),
    error: text("error"),
    started_at: timestamp("started_at"),
    finished_at: timestamp("finished_at"),
  },
  (t) => [index("jobs_install_id_idx").on(t.install_id)],
);

/** Job log lines, written in batches per step. */
export const job_logs = sqliteTable(
  "job_logs",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    job_id: text("job_id")
      .notNull()
      .references(() => jobs.id),
    ts: timestamp("ts").notNull(),
    level: text("level", { enum: LOG_LEVELS }).notNull(),
    message: text("message").notNull(),
    data_json: text("data_json"),
  },
  (t) => [index("job_logs_job_id_idx").on(t.job_id)],
);

/** Recovery data taken before an update (glossary: snapshot). */
export const snapshots = sqliteTable(
  "snapshots",
  {
    id: text("id").primaryKey(),
    install_id: text("install_id")
      .notNull()
      .references(() => installs.id),
    job_id: text("job_id")
      .notNull()
      .references(() => jobs.id),
    worker_version_id: text("worker_version_id").notNull(),
    /** `{ [database_id]: bookmark }` */
    d1_bookmarks_json: text("d1_bookmarks_json").notNull(),
    taken_at: timestamp("taken_at").notNull(),
  },
  (t) => [index("snapshots_install_id_idx").on(t.install_id)],
);
