import { index, integer, primaryKey, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { user } from "./auth-schema";

/**
 * The manager's D1 schema. Better Auth's tables (`user`, `session`,
 * `account`, `verification`, `rate_limit`, with the admin plugin's fields, and
 * the passkey plugin's `passkey`) live in
 * `auth-schema.ts`, generated by Better Auth's CLI, and the notification
 * tables in `notifications/schema.ts`; both are re-exported here so
 * drizzle-kit sees one schema. Timestamps are integer epoch milliseconds.
 */
export * from "../notifications/schema";
export * from "./auth-schema";

const timestamp = (name: string) => integer(name, { mode: "timestamp_ms" });

export const INSTALL_STATUSES = [
  "installing",
  "installed",
  "updating",
  "failed",
  "uninstalling",
  "uninstalled",
] as const;

/**
 * The last health check of an install's Worker URL: `verified` (it answered,
 * anything but a 5xx), `unverified` (no answer, or the edge's route-not-live
 * page), `unhealthy` (it answered with a 5xx).
 */
export const HEALTH_STATUSES = ["verified", "unverified", "unhealthy"] as const;
export type HealthStatus = (typeof HEALTH_STATUSES)[number];

export const RESOURCE_KINDS = [
  "worker",
  "kv",
  "d1",
  "r2",
  "queue",
  "queue_consumer",
  "vectorize",
  "durable_object",
  "workflow",
  "cron",
  "secret",
  "subdomain",
  "ratelimit",
  "domain",
  "email_route",
] as const;

/**
 * How an install's running code was built: `artifact`, a release catalog CI
 * built and signed; `sandbox`, built from the pinned commit by the sandbox
 * Worker in this account, unsigned; `self-deploying`, deployed by the app's
 * own installer, which the sandbox Worker ran at the pinned commit with the
 * app's own token. For a self-deploying install, `manifest_json` holds the
 * catalog manifest (there is no artifact manifest), `artifact_url` and
 * `artifact_digest` name the published catalog manifest, `worker_name` is
 * the Worker that serves the app, and every resource is `managed_by: "app"`.
 */
export const BUILD_KINDS = ["artifact", "sandbox", "self-deploying"] as const;
export type BuildKind = (typeof BUILD_KINDS)[number];

/**
 * Who owns a resource's lifecycle: `appflare`, which created it and deletes
 * it on uninstall, or `app`, the app's own installer, which the manager only
 * records and never deletes.
 */
export const RESOURCE_MANAGERS = ["appflare", "app"] as const;

/**
 * `reconfigure` redeploys an installed app's current version with changed
 * settings (vars), secrets, or Email Routing zone.
 */
export const JOB_KINDS = [
  "install",
  "update",
  "uninstall",
  "rollback",
  "self_update",
  "reconfigure",
] as const;
export type JobKind = (typeof JOB_KINDS)[number];

export const JOB_STATUSES = ["queued", "running", "succeeded", "failed"] as const;

export const LOG_LEVELS = ["debug", "info", "warn", "error"] as const;

/**
 * Key/value manager state: `schema_version` (3.1.4), the `migration_lock` row,
 * and later the discovered account id and Worker name (3.1.1).
 */
export const settings = sqliteTable("settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updated_at: timestamp("updated_at").notNull(),
});

/** One installed app instance (glossary: install). `id` is a ULID. */
export const installs = sqliteTable("installs", {
  id: text("id").primaryKey(),
  app_slug: text("app_slug").notNull(),
  /** The unique key of an active install: two installs that are not uninstalled never share it. */
  worker_name: text("worker_name").notNull(),
  /** User-visible label; defaults to the Worker name. */
  instance_name: text("instance_name"),
  catalog_version: text("catalog_version").notNull(),
  artifact_url: text("artifact_url").notNull(),
  artifact_digest: text("artifact_digest"),
  pin_sha: text("pin_sha"),
  status: text("status", { enum: INSTALL_STATUSES }).notNull(),
  /** Workers version id currently deployed. */
  current_version_id: text("current_version_id"),
  /** User-entered vars (never secrets). */
  config_json: text("config_json"),
  /** Snapshot of the artifact manifest the install was made from. */
  manifest_json: text("manifest_json"),
  /**
   * The last Durable Object migration tag applied to the Worker; null when it
   * has none (or, for installs made before this was recorded, the last tag of
   * `manifest_json`).
   */
  do_migration_tag: text("do_migration_tag"),
  /** How the running code was built (see `BUILD_KINDS`). */
  build_kind: text("build_kind", { enum: BUILD_KINDS }).notNull().default("artifact"),
  /** For a sandbox build: the container image that built it. */
  sandbox_image: text("sandbox_image"),
  /** For a sandbox build: when the build finished. */
  built_at: timestamp("built_at"),
  /** The last health check's result; null until one ran. Never fails a job. */
  health_status: text("health_status", { enum: HEALTH_STATUSES }),
  /** When the last health check probed the Worker. */
  health_checked_at: timestamp("health_checked_at"),
  installed_at: timestamp("installed_at").notNull(),
  updated_at: timestamp("updated_at").notNull(),
  /** Set when the uninstall job finishes (status `uninstalled`). */
  uninstalled_at: timestamp("uninstalled_at"),
  /**
   * Set when an admin forgets an uninstalled install: it leaves the list of
   * removed apps. Its row, its jobs, and any resources it kept in the account
   * stay as they are.
   */
  forgotten_at: timestamp("forgotten_at"),
});

/** A Cloudflare object created for an install (glossary: resource). */
export const resources = sqliteTable(
  "resources",
  {
    id: text("id").primaryKey(),
    install_id: text("install_id")
      .notNull()
      .references(() => installs.id),
    kind: text("kind", { enum: RESOURCE_KINDS }).notNull(),
    binding: text("binding"),
    name: text("name").notNull(),
    cf_id: text("cf_id"),
    created_at: timestamp("created_at").notNull(),
    /** Deleted from the account (by an uninstall). */
    deleted_at: timestamp("deleted_at"),
    /** Kept in the account when its install was uninstalled, so it stays findable. */
    retained_at: timestamp("retained_at"),
    /** Who deletes it: Appflare, or the app's own installer (never Appflare). */
    managed_by: text("managed_by", { enum: RESOURCE_MANAGERS }).notNull().default("appflare"),
  },
  (t) => [index("resources_install_id_idx").on(t.install_id)],
);

/** One asynchronous operation, run as a `JobWorkflow` instance (glossary: job). */
export const jobs = sqliteTable(
  "jobs",
  {
    id: text("id").primaryKey(),
    install_id: text("install_id").references(() => installs.id),
    kind: text("kind", { enum: JOB_KINDS }).notNull(),
    status: text("status", { enum: JOB_STATUSES }).notNull(),
    workflow_instance_id: text("workflow_instance_id"),
    /** Job input with secret values removed (names only). */
    input_json: text("input_json"),
    error: text("error"),
    /** The Workers version the job uploaded (update) or deployed (rollback). */
    worker_version_id: text("worker_version_id"),
    /**
     * Self-update only: the Appflare version the job is promoting, written
     * right before the promotion. The new version completes a job left
     * running only when this names it, so a preview request (which runs the
     * new code before the switch) can never complete the job.
     */
    promoting_version: text("promoting_version"),
    started_at: timestamp("started_at"),
    finished_at: timestamp("finished_at"),
  },
  (t) => [index("jobs_install_id_idx").on(t.install_id)],
);

/** Job log lines, written in batches per step. */
export const job_logs = sqliteTable(
  "job_logs",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    job_id: text("job_id")
      .notNull()
      .references(() => jobs.id),
    ts: timestamp("ts").notNull(),
    level: text("level", { enum: LOG_LEVELS }).notNull(),
    message: text("message").notNull(),
    data_json: text("data_json"),
  },
  (t) => [index("job_logs_job_id_idx").on(t.job_id)],
);

/**
 * Recovery data taken before an update or a settings change (glossary:
 * snapshot): the Worker version that was serving, a D1 Time Travel bookmark
 * per database, and the install's catalog state and settings at that moment,
 * so a rollback can put all of it back.
 * A snapshot of the manager itself (taken by its self-update) has no install:
 * `install_id` is null, `catalog_version` is the manager's version before the
 * update and `target_catalog_version` the one it moved to.
 */
export const snapshots = sqliteTable(
  "snapshots",
  {
    id: text("id").primaryKey(),
    /** Null for a snapshot of the manager itself. */
    install_id: text("install_id").references(() => installs.id),
    /** The update job that took it. */
    job_id: text("job_id")
      .notNull()
      .references(() => jobs.id),
    worker_version_id: text("worker_version_id").notNull(),
    /** `{ [database_id]: bookmark }` */
    d1_bookmarks_json: text("d1_bookmarks_json").notNull(),
    taken_at: timestamp("taken_at").notNull(),
    /** The install's `catalog_version` before the update. */
    catalog_version: text("catalog_version"),
    /** The install's `manifest_json` before the update. */
    manifest_json: text("manifest_json"),
    artifact_url: text("artifact_url"),
    artifact_digest: text("artifact_digest"),
    pin_sha: text("pin_sha"),
    do_migration_tag: text("do_migration_tag"),
    /** The install's build provenance before the update, restored by a rollback. */
    build_kind: text("build_kind", { enum: BUILD_KINDS }).notNull().default("artifact"),
    sandbox_image: text("sandbox_image"),
    built_at: timestamp("built_at"),
    /** The catalog version the update moved to. */
    target_catalog_version: text("target_catalog_version"),
    /**
     * The install's `config_json` (the settings the admin changed) before the
     * job, `{}` when there were none; null for snapshots taken before it was
     * recorded.
     */
    config_json: text("config_json"),
  },
  (t) => [index("snapshots_install_id_idx").on(t.install_id)],
);

/**
 * Sponsored catalog items a user has hidden, by the item's id in the index.
 * Per user, because members browse the catalog too and hiding an item is not
 * a manager setting. A row for an item the index no longer lists is harmless.
 */
export const featured_dismissals = sqliteTable(
  "featured_dismissals",
  {
    user_id: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    item_id: text("item_id").notNull(),
    dismissed_at: timestamp("dismissed_at").notNull(),
  },
  (t) => [primaryKey({ columns: [t.user_id, t.item_id] })],
);
