import {
  ArrowsClockwiseIcon,
  ArticleIcon,
  BellIcon,
  BuildingsIcon,
  CalendarBlankIcon,
  ChartLineIcon,
  ChatCircleIcon,
  CheckSquareIcon,
  CloudIcon,
  CodeIcon,
  CurrencyDollarIcon,
  DesktopIcon,
  EnvelopeSimpleIcon,
  EyeSlashIcon,
  FilmStripIcon,
  FolderIcon,
  GlobeIcon,
  HardDrivesIcon,
  type Icon,
  LinkIcon,
  MegaphoneIcon,
  NotepadIcon,
  PasswordIcon,
  PencilLineIcon,
  PulseIcon,
  RobotIcon,
  ShareNetworkIcon,
  ShieldCheckIcon,
  ShoppingCartIcon,
  SparkleIcon,
  TreeStructureIcon,
  UsersIcon,
  UsersThreeIcon,
  WrenchIcon,
} from "@phosphor-icons/react";

/** An icon per catalog category; any other category gets a cloud. */
const CATEGORY_ICONS: Readonly<Record<string, Icon>> = {
  ai: SparkleIcon,
  analytics: ChartLineIcon,
  blogging: PencilLineIcon,
  bots: RobotIcon,
  business: BuildingsIcon,
  chat: ChatCircleIcon,
  cms: ArticleIcon,
  community: UsersThreeIcon,
  "developer-tools": CodeIcon,
  dns: GlobeIcon,
  ecommerce: ShoppingCartIcon,
  email: EnvelopeSimpleIcon,
  family: UsersIcon,
  files: FolderIcon,
  finance: CurrencyDollarIcon,
  "link-shortener": LinkIcon,
  marketing: MegaphoneIcon,
  media: FilmStripIcon,
  monitoring: PulseIcon,
  networking: TreeStructureIcon,
  notes: NotepadIcon,
  notifications: BellIcon,
  passwords: PasswordIcon,
  privacy: EyeSlashIcon,
  productivity: CheckSquareIcon,
  "remote-access": DesktopIcon,
  scheduling: CalendarBlankIcon,
  security: ShieldCheckIcon,
  sharing: ShareNetworkIcon,
  storage: HardDrivesIcon,
  sync: ArrowsClockwiseIcon,
  utilities: WrenchIcon,
};

/** The icon of a catalog category, decorative (the category's name is always next to it). */
export function CategoryIcon({ category, size = 20 }: { category: string; size?: number }) {
  const CategoryGlyph = CATEGORY_ICONS[category] ?? CloudIcon;
  return <CategoryGlyph size={size} aria-hidden />;
}
