/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppAppsInstallIdRouteImport } from './routes/_app/apps/$installId'
import { Route as AppCatalogIndexRouteImport } from './routes/_app/catalog/index'
import { Route as AppCatalogSlugRouteImport } from './routes/_app/catalog/$slug'
import { Route as AppJobsJobIdRouteImport } from './routes/_app/jobs/$jobId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsRemovedAppsRouteImport } from './routes/_app/settings/removed-apps'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppsInstallIdRoute = AppAppsInstallIdRouteImport.update({
  id: '/apps/$installId',
  path: '/apps/$installId',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogIndexRoute = AppCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogSlugRoute = AppCatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRemovedAppsRoute = AppSettingsRemovedAppsRouteImport.update({
  id: '/settings/removed-apps',
  path: '/settings/removed-apps',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/health': typeof ApiHealthRoute
  '/apps/$installId': typeof AppAppsInstallIdRoute
  '/catalog/$slug': typeof AppCatalogSlugRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/settings/removed-apps': typeof AppSettingsRemovedAppsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/catalog/': typeof AppCatalogIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AppIndexRoute
  '/apps/$installId': typeof AppAppsInstallIdRoute
  '/catalog/$slug': typeof AppCatalogSlugRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/settings/removed-apps': typeof AppSettingsRemovedAppsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/catalog': typeof AppCatalogIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/': typeof AppIndexRoute
  '/_app/apps/$installId': typeof AppAppsInstallIdRoute
  '/_app/catalog/$slug': typeof AppCatalogSlugRoute
  '/_app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/_app/settings/removed-apps': typeof AppSettingsRemovedAppsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/catalog/': typeof AppCatalogIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/api/health'
    | '/apps/$installId'
    | '/catalog/$slug'
    | '/jobs/$jobId'
    | '/settings/removed-apps'
    | '/api/auth/$'
    | '/catalog/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/api/health'
    | '/'
    | '/apps/$installId'
    | '/catalog/$slug'
    | '/jobs/$jobId'
    | '/settings/removed-apps'
    | '/api/auth/$'
    | '/catalog'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/api/health'
    | '/_app/'
    | '/_app/apps/$installId'
    | '/_app/catalog/$slug'
    | '/_app/jobs/$jobId'
    | '/_app/settings/removed-apps'
    | '/api/auth/$'
    | '/_app/catalog/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/apps/$installId': {
      id: '/_app/apps/$installId'
      path: '/apps/$installId'
      fullPath: '/apps/$installId'
      preLoaderRoute: typeof AppAppsInstallIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/': {
      id: '/_app/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AppCatalogIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/$slug': {
      id: '/_app/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof AppCatalogSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$jobId': {
      id: '/_app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/removed-apps': {
      id: '/_app/settings/removed-apps'
      path: '/settings/removed-apps'
      fullPath: '/settings/removed-apps'
      preLoaderRoute: typeof AppSettingsRemovedAppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAppsInstallIdRoute: typeof AppAppsInstallIdRoute
  AppCatalogSlugRoute: typeof AppCatalogSlugRoute
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppSettingsRemovedAppsRoute: typeof AppSettingsRemovedAppsRoute
  AppCatalogIndexRoute: typeof AppCatalogIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAppsInstallIdRoute: AppAppsInstallIdRoute,
  AppCatalogSlugRoute: AppCatalogSlugRoute,
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppSettingsRemovedAppsRoute: AppSettingsRemovedAppsRoute,
  AppCatalogIndexRoute: AppCatalogIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
