/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppAppsInstallIdRouteImport } from './routes/_app/apps/$installId'
import { Route as AppCatalogIndexRouteImport } from './routes/_app/catalog/index'
import { Route as AppCatalogSlugRouteImport } from './routes/_app/catalog/$slug'
import { Route as AppJobsIndexRouteImport } from './routes/_app/jobs/index'
import { Route as AppJobsJobIdRouteImport } from './routes/_app/jobs/$jobId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppSettingsAppflareUpdatesRouteImport } from './routes/_app/settings/appflare-updates'
import { Route as AppSettingsDomainsRouteImport } from './routes/_app/settings/domains'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings/notifications'
import { Route as AppSettingsRemovedAppsRouteImport } from './routes/_app/settings/removed-apps'
import { Route as AppSettingsUsageDataRouteImport } from './routes/_app/settings/usage-data'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDangerRemoveAppflareRouteImport } from './routes/api/danger/remove-appflare'
import { Route as ApiDangerRotateAuthSecretRouteImport } from './routes/api/danger/rotate-auth-secret'
import { Route as ApiCatalogAvatarHandleRouteImport } from './routes/api/catalog/avatar/$handle'
import { Route as ApiCatalogMediaDigestRouteImport } from './routes/api/catalog/media/$digest'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppsInstallIdRoute = AppAppsInstallIdRouteImport.update({
  id: '/apps/$installId',
  path: '/apps/$installId',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogIndexRoute = AppCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogSlugRoute = AppCatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAppflareUpdatesRoute =
  AppSettingsAppflareUpdatesRouteImport.update({
    id: '/settings/appflare-updates',
    path: '/settings/appflare-updates',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsDomainsRoute = AppSettingsDomainsRouteImport.update({
  id: '/settings/domains',
  path: '/settings/domains',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsRemovedAppsRoute = AppSettingsRemovedAppsRouteImport.update({
  id: '/settings/removed-apps',
  path: '/settings/removed-apps',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsageDataRoute = AppSettingsUsageDataRouteImport.update({
  id: '/settings/usage-data',
  path: '/settings/usage-data',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDangerRemoveAppflareRoute = ApiDangerRemoveAppflareRouteImport.update({
  id: '/api/danger/remove-appflare',
  path: '/api/danger/remove-appflare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDangerRotateAuthSecretRoute =
  ApiDangerRotateAuthSecretRouteImport.update({
    id: '/api/danger/rotate-auth-secret',
    path: '/api/danger/rotate-auth-secret',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCatalogAvatarHandleRoute = ApiCatalogAvatarHandleRouteImport.update({
  id: '/api/catalog/avatar/$handle',
  path: '/api/catalog/avatar/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogMediaDigestRoute = ApiCatalogMediaDigestRouteImport.update({
  id: '/api/catalog/media/$digest',
  path: '/api/catalog/media/$digest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/health': typeof ApiHealthRoute
  '/apps/$installId': typeof AppAppsInstallIdRoute
  '/catalog/$slug': typeof AppCatalogSlugRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/appflare-updates': typeof AppSettingsAppflareUpdatesRoute
  '/settings/domains': typeof AppSettingsDomainsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/removed-apps': typeof AppSettingsRemovedAppsRoute
  '/settings/usage-data': typeof AppSettingsUsageDataRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/danger/remove-appflare': typeof ApiDangerRemoveAppflareRoute
  '/api/danger/rotate-auth-secret': typeof ApiDangerRotateAuthSecretRoute
  '/catalog/': typeof AppCatalogIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/api/catalog/avatar/$handle': typeof ApiCatalogAvatarHandleRoute
  '/api/catalog/media/$digest': typeof ApiCatalogMediaDigestRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AppIndexRoute
  '/apps/$installId': typeof AppAppsInstallIdRoute
  '/catalog/$slug': typeof AppCatalogSlugRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/appflare-updates': typeof AppSettingsAppflareUpdatesRoute
  '/settings/domains': typeof AppSettingsDomainsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/removed-apps': typeof AppSettingsRemovedAppsRoute
  '/settings/usage-data': typeof AppSettingsUsageDataRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/danger/remove-appflare': typeof ApiDangerRemoveAppflareRoute
  '/api/danger/rotate-auth-secret': typeof ApiDangerRotateAuthSecretRoute
  '/catalog': typeof AppCatalogIndexRoute
  '/jobs': typeof AppJobsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/api/catalog/avatar/$handle': typeof ApiCatalogAvatarHandleRoute
  '/api/catalog/media/$digest': typeof ApiCatalogMediaDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/': typeof AppIndexRoute
  '/_app/apps/$installId': typeof AppAppsInstallIdRoute
  '/_app/catalog/$slug': typeof AppCatalogSlugRoute
  '/_app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/appflare-updates': typeof AppSettingsAppflareUpdatesRoute
  '/_app/settings/domains': typeof AppSettingsDomainsRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/removed-apps': typeof AppSettingsRemovedAppsRoute
  '/_app/settings/usage-data': typeof AppSettingsUsageDataRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/danger/remove-appflare': typeof ApiDangerRemoveAppflareRoute
  '/api/danger/rotate-auth-secret': typeof ApiDangerRotateAuthSecretRoute
  '/_app/catalog/': typeof AppCatalogIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/api/catalog/avatar/$handle': typeof ApiCatalogAvatarHandleRoute
  '/api/catalog/media/$digest': typeof ApiCatalogMediaDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/api/health'
    | '/apps/$installId'
    | '/catalog/$slug'
    | '/jobs/$jobId'
    | '/settings/account'
    | '/settings/appflare-updates'
    | '/settings/domains'
    | '/settings/notifications'
    | '/settings/removed-apps'
    | '/settings/usage-data'
    | '/settings/users'
    | '/api/auth/$'
    | '/api/danger/remove-appflare'
    | '/api/danger/rotate-auth-secret'
    | '/catalog/'
    | '/jobs/'
    | '/settings/'
    | '/api/catalog/avatar/$handle'
    | '/api/catalog/media/$digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/api/health'
    | '/'
    | '/apps/$installId'
    | '/catalog/$slug'
    | '/jobs/$jobId'
    | '/settings/account'
    | '/settings/appflare-updates'
    | '/settings/domains'
    | '/settings/notifications'
    | '/settings/removed-apps'
    | '/settings/usage-data'
    | '/settings/users'
    | '/api/auth/$'
    | '/api/danger/remove-appflare'
    | '/api/danger/rotate-auth-secret'
    | '/catalog'
    | '/jobs'
    | '/settings'
    | '/api/catalog/avatar/$handle'
    | '/api/catalog/media/$digest'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/api/health'
    | '/_app/'
    | '/_app/apps/$installId'
    | '/_app/catalog/$slug'
    | '/_app/jobs/$jobId'
    | '/_app/settings/account'
    | '/_app/settings/appflare-updates'
    | '/_app/settings/domains'
    | '/_app/settings/notifications'
    | '/_app/settings/removed-apps'
    | '/_app/settings/usage-data'
    | '/_app/settings/users'
    | '/api/auth/$'
    | '/api/danger/remove-appflare'
    | '/api/danger/rotate-auth-secret'
    | '/_app/catalog/'
    | '/_app/jobs/'
    | '/_app/settings/'
    | '/api/catalog/avatar/$handle'
    | '/api/catalog/media/$digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDangerRemoveAppflareRoute: typeof ApiDangerRemoveAppflareRoute
  ApiDangerRotateAuthSecretRoute: typeof ApiDangerRotateAuthSecretRoute
  ApiCatalogAvatarHandleRoute: typeof ApiCatalogAvatarHandleRoute
  ApiCatalogMediaDigestRoute: typeof ApiCatalogMediaDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/apps/$installId': {
      id: '/_app/apps/$installId'
      path: '/apps/$installId'
      fullPath: '/apps/$installId'
      preLoaderRoute: typeof AppAppsInstallIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/': {
      id: '/_app/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AppCatalogIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/$slug': {
      id: '/_app/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof AppCatalogSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$jobId': {
      id: '/_app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/appflare-updates': {
      id: '/_app/settings/appflare-updates'
      path: '/settings/appflare-updates'
      fullPath: '/settings/appflare-updates'
      preLoaderRoute: typeof AppSettingsAppflareUpdatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/domains': {
      id: '/_app/settings/domains'
      path: '/settings/domains'
      fullPath: '/settings/domains'
      preLoaderRoute: typeof AppSettingsDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/removed-apps': {
      id: '/_app/settings/removed-apps'
      path: '/settings/removed-apps'
      fullPath: '/settings/removed-apps'
      preLoaderRoute: typeof AppSettingsRemovedAppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/usage-data': {
      id: '/_app/settings/usage-data'
      path: '/settings/usage-data'
      fullPath: '/settings/usage-data'
      preLoaderRoute: typeof AppSettingsUsageDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/danger/remove-appflare': {
      id: '/api/danger/remove-appflare'
      path: '/api/danger/remove-appflare'
      fullPath: '/api/danger/remove-appflare'
      preLoaderRoute: typeof ApiDangerRemoveAppflareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/danger/rotate-auth-secret': {
      id: '/api/danger/rotate-auth-secret'
      path: '/api/danger/rotate-auth-secret'
      fullPath: '/api/danger/rotate-auth-secret'
      preLoaderRoute: typeof ApiDangerRotateAuthSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/avatar/$handle': {
      id: '/api/catalog/avatar/$handle'
      path: '/api/catalog/avatar/$handle'
      fullPath: '/api/catalog/avatar/$handle'
      preLoaderRoute: typeof ApiCatalogAvatarHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/media/$digest': {
      id: '/api/catalog/media/$digest'
      path: '/api/catalog/media/$digest'
      fullPath: '/api/catalog/media/$digest'
      preLoaderRoute: typeof ApiCatalogMediaDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAppsInstallIdRoute: typeof AppAppsInstallIdRoute
  AppCatalogSlugRoute: typeof AppCatalogSlugRoute
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsAppflareUpdatesRoute: typeof AppSettingsAppflareUpdatesRoute
  AppSettingsDomainsRoute: typeof AppSettingsDomainsRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsRemovedAppsRoute: typeof AppSettingsRemovedAppsRoute
  AppSettingsUsageDataRoute: typeof AppSettingsUsageDataRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppCatalogIndexRoute: typeof AppCatalogIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAppsInstallIdRoute: AppAppsInstallIdRoute,
  AppCatalogSlugRoute: AppCatalogSlugRoute,
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsAppflareUpdatesRoute: AppSettingsAppflareUpdatesRoute,
  AppSettingsDomainsRoute: AppSettingsDomainsRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsRemovedAppsRoute: AppSettingsRemovedAppsRoute,
  AppSettingsUsageDataRoute: AppSettingsUsageDataRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppCatalogIndexRoute: AppCatalogIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDangerRemoveAppflareRoute: ApiDangerRemoveAppflareRoute,
  ApiDangerRotateAuthSecretRoute: ApiDangerRotateAuthSecretRoute,
  ApiCatalogAvatarHandleRoute: ApiCatalogAvatarHandleRoute,
  ApiCatalogMediaDigestRoute: ApiCatalogMediaDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
