/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppAppsInstallIdRouteImport } from './routes/_app/apps/$installId'
import { Route as AppCatalogIndexRouteImport } from './routes/_app/catalog/index'
import { Route as AppCatalogSlugRouteImport } from './routes/_app/catalog/$slug'
import { Route as AppInstallSlugRouteImport } from './routes/_app/install/$slug'
import { Route as AppJobsIndexRouteImport } from './routes/_app/jobs/index'
import { Route as AppJobsJobIdRouteImport } from './routes/_app/jobs/$jobId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppSettingsAppflareUpdatesRouteImport } from './routes/_app/settings/appflare-updates'
import { Route as AppSettingsBuildingRouteImport } from './routes/_app/settings/building'
import { Route as AppSettingsCatalogsRouteImport } from './routes/_app/settings/catalogs'
import { Route as AppSettingsDomainsRouteImport } from './routes/_app/settings/domains'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings/notifications'
import { Route as AppSettingsRemovedAppsRouteImport } from './routes/_app/settings/removed-apps'
import { Route as AppSettingsUpdatesRouteImport } from './routes/_app/settings/updates'
import { Route as AppSettingsUsageDataRouteImport } from './routes/_app/settings/usage-data'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDangerRemoveAppflareRouteImport } from './routes/api/danger/remove-appflare'
import { Route as ApiDangerRotateAuthSecretRouteImport } from './routes/api/danger/rotate-auth-secret'
import { Route as AppCatalogSourceBuildIdRouteImport } from './routes/_app/catalog/source.$buildId'
import { Route as ApiCatalogAvatarHandleRouteImport } from './routes/api/catalog/avatar/$handle'
import { Route as ApiCatalogMediaDigestRouteImport } from './routes/api/catalog/media/$digest'
import { Route as AppInstallGithubOwnerRepoRouteImport } from './routes/_app/install/github/$owner/$repo'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppsInstallIdRoute = AppAppsInstallIdRouteImport.update({
  id: '/apps/$installId',
  path: '/apps/$installId',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogIndexRoute = AppCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogSlugRoute = AppCatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppInstallSlugRoute = AppInstallSlugRouteImport.update({
  id: '/install/$slug',
  path: '/install/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAppflareUpdatesRoute =
  AppSettingsAppflareUpdatesRouteImport.update({
    id: '/settings/appflare-updates',
    path: '/settings/appflare-updates',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsBuildingRoute = AppSettingsBuildingRouteImport.update({
  id: '/settings/building',
  path: '/settings/building',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCatalogsRoute = AppSettingsCatalogsRouteImport.update({
  id: '/settings/catalogs',
  path: '/settings/catalogs',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsDomainsRoute = AppSettingsDomainsRouteImport.update({
  id: '/settings/domains',
  path: '/settings/domains',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsRemovedAppsRoute = AppSettingsRemovedAppsRouteImport.update({
  id: '/settings/removed-apps',
  path: '/settings/removed-apps',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUpdatesRoute = AppSettingsUpdatesRouteImport.update({
  id: '/settings/updates',
  path: '/settings/updates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsageDataRoute = AppSettingsUsageDataRouteImport.update({
  id: '/settings/usage-data',
  path: '/settings/usage-data',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDangerRemoveAppflareRoute = ApiDangerRemoveAppflareRouteImport.update({
  id: '/api/danger/remove-appflare',
  path: '/api/danger/remove-appflare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDangerRotateAuthSecretRoute =
  ApiDangerRotateAuthSecretRouteImport.update({
    id: '/api/danger/rotate-auth-secret',
    path: '/api/danger/rotate-auth-secret',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCatalogSourceBuildIdRoute = AppCatalogSourceBuildIdRouteImport.update({
  id: '/catalog/source/$buildId',
  path: '/catalog/source/$buildId',
  getParentRoute: () => AppRoute,
} as any)
const ApiCatalogAvatarHandleRoute = ApiCatalogAvatarHandleRouteImport.update({
  id: '/api/catalog/avatar/$handle',
  path: '/api/catalog/avatar/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogMediaDigestRoute = ApiCatalogMediaDigestRouteImport.update({
  id: '/api/catalog/media/$digest',
  path: '/api/catalog/media/$digest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInstallGithubOwnerRepoRoute =
  AppInstallGithubOwnerRepoRouteImport.update({
    id: '/install/github/$owner/$repo',
    path: '/install/github/$owner/$repo',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/api/health': typeof ApiHealthRoute
  '/apps/$installId': typeof AppAppsInstallIdRoute
  '/catalog/$slug': typeof AppCatalogSlugRoute
  '/install/$slug': typeof AppInstallSlugRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/appflare-updates': typeof AppSettingsAppflareUpdatesRoute
  '/settings/building': typeof AppSettingsBuildingRoute
  '/settings/catalogs': typeof AppSettingsCatalogsRoute
  '/settings/domains': typeof AppSettingsDomainsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/removed-apps': typeof AppSettingsRemovedAppsRoute
  '/settings/updates': typeof AppSettingsUpdatesRoute
  '/settings/usage-data': typeof AppSettingsUsageDataRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/danger/remove-appflare': typeof ApiDangerRemoveAppflareRoute
  '/api/danger/rotate-auth-secret': typeof ApiDangerRotateAuthSecretRoute
  '/catalog/': typeof AppCatalogIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/catalog/source/$buildId': typeof AppCatalogSourceBuildIdRoute
  '/api/catalog/avatar/$handle': typeof ApiCatalogAvatarHandleRoute
  '/api/catalog/media/$digest': typeof ApiCatalogMediaDigestRoute
  '/install/github/$owner/$repo': typeof AppInstallGithubOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AppIndexRoute
  '/apps/$installId': typeof AppAppsInstallIdRoute
  '/catalog/$slug': typeof AppCatalogSlugRoute
  '/install/$slug': typeof AppInstallSlugRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/appflare-updates': typeof AppSettingsAppflareUpdatesRoute
  '/settings/building': typeof AppSettingsBuildingRoute
  '/settings/catalogs': typeof AppSettingsCatalogsRoute
  '/settings/domains': typeof AppSettingsDomainsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/removed-apps': typeof AppSettingsRemovedAppsRoute
  '/settings/updates': typeof AppSettingsUpdatesRoute
  '/settings/usage-data': typeof AppSettingsUsageDataRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/danger/remove-appflare': typeof ApiDangerRemoveAppflareRoute
  '/api/danger/rotate-auth-secret': typeof ApiDangerRotateAuthSecretRoute
  '/catalog': typeof AppCatalogIndexRoute
  '/jobs': typeof AppJobsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/catalog/source/$buildId': typeof AppCatalogSourceBuildIdRoute
  '/api/catalog/avatar/$handle': typeof ApiCatalogAvatarHandleRoute
  '/api/catalog/media/$digest': typeof ApiCatalogMediaDigestRoute
  '/install/github/$owner/$repo': typeof AppInstallGithubOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/': typeof AppIndexRoute
  '/_app/apps/$installId': typeof AppAppsInstallIdRoute
  '/_app/catalog/$slug': typeof AppCatalogSlugRoute
  '/_app/install/$slug': typeof AppInstallSlugRoute
  '/_app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/appflare-updates': typeof AppSettingsAppflareUpdatesRoute
  '/_app/settings/building': typeof AppSettingsBuildingRoute
  '/_app/settings/catalogs': typeof AppSettingsCatalogsRoute
  '/_app/settings/domains': typeof AppSettingsDomainsRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/removed-apps': typeof AppSettingsRemovedAppsRoute
  '/_app/settings/updates': typeof AppSettingsUpdatesRoute
  '/_app/settings/usage-data': typeof AppSettingsUsageDataRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/danger/remove-appflare': typeof ApiDangerRemoveAppflareRoute
  '/api/danger/rotate-auth-secret': typeof ApiDangerRotateAuthSecretRoute
  '/_app/catalog/': typeof AppCatalogIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/catalog/source/$buildId': typeof AppCatalogSourceBuildIdRoute
  '/api/catalog/avatar/$handle': typeof ApiCatalogAvatarHandleRoute
  '/api/catalog/media/$digest': typeof ApiCatalogMediaDigestRoute
  '/_app/install/github/$owner/$repo': typeof AppInstallGithubOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/api/health'
    | '/apps/$installId'
    | '/catalog/$slug'
    | '/install/$slug'
    | '/jobs/$jobId'
    | '/settings/account'
    | '/settings/appflare-updates'
    | '/settings/building'
    | '/settings/catalogs'
    | '/settings/domains'
    | '/settings/notifications'
    | '/settings/removed-apps'
    | '/settings/updates'
    | '/settings/usage-data'
    | '/settings/users'
    | '/api/auth/$'
    | '/api/danger/remove-appflare'
    | '/api/danger/rotate-auth-secret'
    | '/catalog/'
    | '/jobs/'
    | '/settings/'
    | '/catalog/source/$buildId'
    | '/api/catalog/avatar/$handle'
    | '/api/catalog/media/$digest'
    | '/install/github/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/api/health'
    | '/'
    | '/apps/$installId'
    | '/catalog/$slug'
    | '/install/$slug'
    | '/jobs/$jobId'
    | '/settings/account'
    | '/settings/appflare-updates'
    | '/settings/building'
    | '/settings/catalogs'
    | '/settings/domains'
    | '/settings/notifications'
    | '/settings/removed-apps'
    | '/settings/updates'
    | '/settings/usage-data'
    | '/settings/users'
    | '/api/auth/$'
    | '/api/danger/remove-appflare'
    | '/api/danger/rotate-auth-secret'
    | '/catalog'
    | '/jobs'
    | '/settings'
    | '/catalog/source/$buildId'
    | '/api/catalog/avatar/$handle'
    | '/api/catalog/media/$digest'
    | '/install/github/$owner/$repo'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/api/health'
    | '/_app/'
    | '/_app/apps/$installId'
    | '/_app/catalog/$slug'
    | '/_app/install/$slug'
    | '/_app/jobs/$jobId'
    | '/_app/settings/account'
    | '/_app/settings/appflare-updates'
    | '/_app/settings/building'
    | '/_app/settings/catalogs'
    | '/_app/settings/domains'
    | '/_app/settings/notifications'
    | '/_app/settings/removed-apps'
    | '/_app/settings/updates'
    | '/_app/settings/usage-data'
    | '/_app/settings/users'
    | '/api/auth/$'
    | '/api/danger/remove-appflare'
    | '/api/danger/rotate-auth-secret'
    | '/_app/catalog/'
    | '/_app/jobs/'
    | '/_app/settings/'
    | '/_app/catalog/source/$buildId'
    | '/api/catalog/avatar/$handle'
    | '/api/catalog/media/$digest'
    | '/_app/install/github/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDangerRemoveAppflareRoute: typeof ApiDangerRemoveAppflareRoute
  ApiDangerRotateAuthSecretRoute: typeof ApiDangerRotateAuthSecretRoute
  ApiCatalogAvatarHandleRoute: typeof ApiCatalogAvatarHandleRoute
  ApiCatalogMediaDigestRoute: typeof ApiCatalogMediaDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/apps/$installId': {
      id: '/_app/apps/$installId'
      path: '/apps/$installId'
      fullPath: '/apps/$installId'
      preLoaderRoute: typeof AppAppsInstallIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/': {
      id: '/_app/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AppCatalogIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/$slug': {
      id: '/_app/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof AppCatalogSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/install/$slug': {
      id: '/_app/install/$slug'
      path: '/install/$slug'
      fullPath: '/install/$slug'
      preLoaderRoute: typeof AppInstallSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$jobId': {
      id: '/_app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/appflare-updates': {
      id: '/_app/settings/appflare-updates'
      path: '/settings/appflare-updates'
      fullPath: '/settings/appflare-updates'
      preLoaderRoute: typeof AppSettingsAppflareUpdatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/building': {
      id: '/_app/settings/building'
      path: '/settings/building'
      fullPath: '/settings/building'
      preLoaderRoute: typeof AppSettingsBuildingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/catalogs': {
      id: '/_app/settings/catalogs'
      path: '/settings/catalogs'
      fullPath: '/settings/catalogs'
      preLoaderRoute: typeof AppSettingsCatalogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/domains': {
      id: '/_app/settings/domains'
      path: '/settings/domains'
      fullPath: '/settings/domains'
      preLoaderRoute: typeof AppSettingsDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/removed-apps': {
      id: '/_app/settings/removed-apps'
      path: '/settings/removed-apps'
      fullPath: '/settings/removed-apps'
      preLoaderRoute: typeof AppSettingsRemovedAppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/updates': {
      id: '/_app/settings/updates'
      path: '/settings/updates'
      fullPath: '/settings/updates'
      preLoaderRoute: typeof AppSettingsUpdatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/usage-data': {
      id: '/_app/settings/usage-data'
      path: '/settings/usage-data'
      fullPath: '/settings/usage-data'
      preLoaderRoute: typeof AppSettingsUsageDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/danger/remove-appflare': {
      id: '/api/danger/remove-appflare'
      path: '/api/danger/remove-appflare'
      fullPath: '/api/danger/remove-appflare'
      preLoaderRoute: typeof ApiDangerRemoveAppflareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/danger/rotate-auth-secret': {
      id: '/api/danger/rotate-auth-secret'
      path: '/api/danger/rotate-auth-secret'
      fullPath: '/api/danger/rotate-auth-secret'
      preLoaderRoute: typeof ApiDangerRotateAuthSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/catalog/source/$buildId': {
      id: '/_app/catalog/source/$buildId'
      path: '/catalog/source/$buildId'
      fullPath: '/catalog/source/$buildId'
      preLoaderRoute: typeof AppCatalogSourceBuildIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/catalog/avatar/$handle': {
      id: '/api/catalog/avatar/$handle'
      path: '/api/catalog/avatar/$handle'
      fullPath: '/api/catalog/avatar/$handle'
      preLoaderRoute: typeof ApiCatalogAvatarHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/media/$digest': {
      id: '/api/catalog/media/$digest'
      path: '/api/catalog/media/$digest'
      fullPath: '/api/catalog/media/$digest'
      preLoaderRoute: typeof ApiCatalogMediaDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/install/github/$owner/$repo': {
      id: '/_app/install/github/$owner/$repo'
      path: '/install/github/$owner/$repo'
      fullPath: '/install/github/$owner/$repo'
      preLoaderRoute: typeof AppInstallGithubOwnerRepoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAppsInstallIdRoute: typeof AppAppsInstallIdRoute
  AppCatalogSlugRoute: typeof AppCatalogSlugRoute
  AppInstallSlugRoute: typeof AppInstallSlugRoute
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsAppflareUpdatesRoute: typeof AppSettingsAppflareUpdatesRoute
  AppSettingsBuildingRoute: typeof AppSettingsBuildingRoute
  AppSettingsCatalogsRoute: typeof AppSettingsCatalogsRoute
  AppSettingsDomainsRoute: typeof AppSettingsDomainsRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsRemovedAppsRoute: typeof AppSettingsRemovedAppsRoute
  AppSettingsUpdatesRoute: typeof AppSettingsUpdatesRoute
  AppSettingsUsageDataRoute: typeof AppSettingsUsageDataRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppCatalogIndexRoute: typeof AppCatalogIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppCatalogSourceBuildIdRoute: typeof AppCatalogSourceBuildIdRoute
  AppInstallGithubOwnerRepoRoute: typeof AppInstallGithubOwnerRepoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAppsInstallIdRoute: AppAppsInstallIdRoute,
  AppCatalogSlugRoute: AppCatalogSlugRoute,
  AppInstallSlugRoute: AppInstallSlugRoute,
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsAppflareUpdatesRoute: AppSettingsAppflareUpdatesRoute,
  AppSettingsBuildingRoute: AppSettingsBuildingRoute,
  AppSettingsCatalogsRoute: AppSettingsCatalogsRoute,
  AppSettingsDomainsRoute: AppSettingsDomainsRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsRemovedAppsRoute: AppSettingsRemovedAppsRoute,
  AppSettingsUpdatesRoute: AppSettingsUpdatesRoute,
  AppSettingsUsageDataRoute: AppSettingsUsageDataRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppCatalogIndexRoute: AppCatalogIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppCatalogSourceBuildIdRoute: AppCatalogSourceBuildIdRoute,
  AppInstallGithubOwnerRepoRoute: AppInstallGithubOwnerRepoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDangerRemoveAppflareRoute: ApiDangerRemoveAppflareRoute,
  ApiDangerRotateAuthSecretRoute: ApiDangerRotateAuthSecretRoute,
  ApiCatalogAvatarHandleRoute: ApiCatalogAvatarHandleRoute,
  ApiCatalogMediaDigestRoute: ApiCatalogMediaDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
