// Generated by scripts/gen-migrations-index.mjs from meta/_journal.json. Do not edit.

import m0000 from "./0000_init.sql?raw";

/** Every migration in apply order. `schema_version` counts how many have been applied. */
export const migrations: readonly { tag: string; sql: string }[] = [
  { tag: "0000_init", sql: m0000 },
];
