// Generated by scripts/gen-migrations-index.mjs from meta/_journal.json. Do not edit.

import m0000 from "./0000_init.sql?raw";
import m0001 from "./0001_rate_limit.sql?raw";
import m0002 from "./0002_uninstall.sql?raw";
import m0003 from "./0003_update_snapshots.sql?raw";
import m0004 from "./0004_manager_snapshots.sql?raw";
import m0005 from "./0005_self_update_promotion.sql?raw";
import m0006 from "./0006_install_health.sql?raw";
import m0007 from "./0007_passkeys.sql?raw";
import m0008 from "./0008_build_tiers.sql?raw";
import m0009 from "./0009_forgotten_installs.sql?raw";
import m0010 from "./0010_featured_dismissals.sql?raw";
import m0011 from "./0011_snapshot_settings.sql?raw";
import m0012 from "./0012_notification_channels.sql?raw";
import m0013 from "./0013_update_control.sql?raw";

/** Every migration in apply order. `schema_version` counts how many have been applied. */
export const migrations: readonly { tag: string; sql: string }[] = [
  { tag: "0000_init", sql: m0000 },
  { tag: "0001_rate_limit", sql: m0001 },
  { tag: "0002_uninstall", sql: m0002 },
  { tag: "0003_update_snapshots", sql: m0003 },
  { tag: "0004_manager_snapshots", sql: m0004 },
  { tag: "0005_self_update_promotion", sql: m0005 },
  { tag: "0006_install_health", sql: m0006 },
  { tag: "0007_passkeys", sql: m0007 },
  { tag: "0008_build_tiers", sql: m0008 },
  { tag: "0009_forgotten_installs", sql: m0009 },
  { tag: "0010_featured_dismissals", sql: m0010 },
  { tag: "0011_snapshot_settings", sql: m0011 },
  { tag: "0012_notification_channels", sql: m0012 },
  { tag: "0013_update_control", sql: m0013 },
];
