CREATE TABLE `installations` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`worker_name` text NOT NULL,
	`hostname` text,
	`zone_id` text,
	`address` text NOT NULL,
	`workers_dev_subdomain` text,
	`release_version` text NOT NULL,
	`release_digest` text NOT NULL,
	`release_manifest` text NOT NULL,
	`release_zip_url` text NOT NULL,
	`release_key_id` text NOT NULL,
	`key_hash` text NOT NULL,
	`handoff_hash` text NOT NULL,
	`status` text NOT NULL,
	`step` text NOT NULL,
	`message` text,
	`d1_name` text NOT NULL,
	`d1_id` text,
	`d1_attempt_at` integer,
	`kv_title` text NOT NULL,
	`kv_id` text,
	`kv_attempt_at` integer,
	`worker_created` integer DEFAULT false NOT NULL,
	`worker_attempt_at` integer,
	`workflow_name` text NOT NULL,
	`workflow_created` integer DEFAULT false NOT NULL,
	`domain_id` text,
	`asset_rounds` integer DEFAULT 0 NOT NULL,
	`proof_attempts` integer DEFAULT 0 NOT NULL,
	`lease_owner` text,
	`lease_until` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `installations_account` ON `installations` (`account_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `installations_account_worker` ON `installations` (`account_id`,`worker_name`);