// Generated by scripts/gen-migrations-index.mjs from meta/_journal.json. Do not edit.

/** Every migration in apply order; the n-th is recorded as version n + 1. */
export const migrations: readonly { tag: string; sql: string }[] = [
  {
    tag: "0000_init",
    sql: "CREATE TABLE `installations` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`account_id` text NOT NULL,\n\t`worker_name` text NOT NULL,\n\t`hostname` text,\n\t`zone_id` text,\n\t`address` text NOT NULL,\n\t`workers_dev_subdomain` text,\n\t`release_version` text NOT NULL,\n\t`release_digest` text NOT NULL,\n\t`release_manifest` text NOT NULL,\n\t`release_zip_url` text NOT NULL,\n\t`release_key_id` text NOT NULL,\n\t`key_hash` text NOT NULL,\n\t`handoff_hash` text NOT NULL,\n\t`status` text NOT NULL,\n\t`step` text NOT NULL,\n\t`message` text,\n\t`d1_name` text NOT NULL,\n\t`d1_id` text,\n\t`d1_attempt_at` integer,\n\t`kv_title` text NOT NULL,\n\t`kv_id` text,\n\t`kv_attempt_at` integer,\n\t`worker_created` integer DEFAULT false NOT NULL,\n\t`worker_attempt_at` integer,\n\t`workflow_name` text NOT NULL,\n\t`workflow_created` integer DEFAULT false NOT NULL,\n\t`domain_id` text,\n\t`asset_rounds` integer DEFAULT 0 NOT NULL,\n\t`proof_attempts` integer DEFAULT 0 NOT NULL,\n\t`lease_owner` text,\n\t`lease_until` integer,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `installations_account` ON `installations` (`account_id`);--> statement-breakpoint\nCREATE UNIQUE INDEX `installations_account_worker` ON `installations` (`account_id`,`worker_name`);",
  },
];
